[project]
name = "molgr"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["scikit-build-core>=0.10", "setuptools-scm", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.build-type = "Release"
wheel.packages = ["src/molgr"]

# ✅ 这是官方原生支持的 Provider
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"

# 生成 _version.py (包含在 sdist 中)
sdist.include = ["src/molgr/_version.py"]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=6.0.0",
    "rich>=14.2.0",
    "ruff>=0.14.9",
]

[tool.ruff]
exclude = [".git", ".venv", "__pycache__", "build", "dist"]
line-length = 100
indent-width = 4
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[tool.ruff.lint]
select = [
    "E",
    "W",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort 
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions 
    "UP",  # pyupgrade 
    "SIM", # flake8-simplify
]
ignore = [
    "E501", # line too long 
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=src --cov-report=term-missing"
testpaths = ["tests"]
pythonpath = ["src"]


[tool.mypy]
warn_return_any = false       # 允许函数返回 Any (这对调用未加类型的第三方库很有用)
warn_unused_configs = true    # 警告无用的配置
explicit_package_bases = true # 配合 src 目录结构

disallow_untyped_defs = false # 关键！允许编写没有类型注解的函数
disallow_any_generics = false # 允许使用 List, Dict 而不必须写 List[int]

check_untyped_defs = true   # 关键！即使函数没写注解，也要检查函数内部的逻辑错误
no_implicit_optional = true # 禁止隐式的 Optional (即禁止 x: str = None)
warn_redundant_casts = true # 警告多余的 cast
warn_unused_ignores = false # 警告多余的 # type: ignore

ignore_missing_imports = true
exclude = ["tests", "scripts", "build", "dist"]


[[tool.uv.index]]
name = "pypi"
url = "https://mirrors.zju.edu.cn/pypi/web/simple"

[[tool.uv.index]]
name = "hong"
url = "http://10.72.201.58:13000/api/packages/tmj/pypi/simple/"
publish-url = "http://10.72.201.58:13000/api/packages/tmj/pypi/"
explicit = true
