"""
Metal handling logic
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['MetalAtomPosition', 'MetalHandler']
class MetalAtomPosition:
    symbol: str
    def __repr__(self) -> str:
        ...
    @property
    def element_idx(self) -> int:
        ...
    @element_idx.setter
    def element_idx(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def idx(self) -> int:
        ...
    @idx.setter
    def idx(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def radical_num(self) -> int:
        ...
    @radical_num.setter
    def radical_num(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def valence(self) -> int:
        ...
    @valence.setter
    def valence(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def z(self) -> float:
        ...
    @z.setter
    def z(self, arg0: typing.SupportsFloat) -> None:
        ...
class MetalHandler:
    @staticmethod
    def combine_metal_with_mol(mol_ptr: typing.SupportsInt, metals: collections.abc.Sequence[MetalAtomPosition]) -> None:
        ...
    def __init__(self, mol_ptr: typing.SupportsInt) -> None:
        ...
    def generate_combinations(self, total_radical_electrons: typing.SupportsInt) -> list[list[MetalAtomPosition]]:
        ...
    def strip_metals(self, mol_ptr: typing.SupportsInt) -> str:
        ...
